hpc <- read.csv("hpc.txt",sep=";")
index <- which(hpc[,1] == "2/2/2007")
plot(hpc[,7], xlab = "", ylab = "Energy sub metering", type = "l", xaxt = "n")
lines(hpc[,8],xlab = "", col = "red")
lines(hpc[,9],xlab = "", col = "blue")
axis(1, at= c("0",as.character(index[1]),"2880"), labels = c("Thu","Fri","Sat"), xlab = "")
leg_txt <- c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
legend("topright",leg_txt, text.col = c("black","red","blue"), lty = c(1,1,1), col = c("black","red","blue"), cex = 0.7)
dev.copy(png, file = "plot3.png",width = 480, height = 480)
dev.off()
